import React from "react";
import Head from "next/head";

const HomePage = () => (
  <div>
    <Head>
      <title>Livreurs</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>Hi</div>
  </div>
);

HomePage.requireAuth = true;

export default HomePage;
