import type { NextPage } from "next";
import Head from "next/head";

const HomePage: NextPage = () => (
  <div>
    <Head>
      <title>Livreurs</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>Hi</div>
  </div>
);
export default HomePage;
