import { LoadingPage, Section } from "@ceseatslib/template";
import { ActionCard } from "@ceseatslib/ui";
import { INotificationType, useNotificationCenter } from "@ceseatslib/utils";
import { Container } from "@mui/material";
import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import s from "styles/Stats.module.scss";

const Stats = () => {
  const [stats, setStats] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const { createNotification } = useNotificationCenter();

  useEffect(() => {
    setIsLoading(true);
    axios
      .get(`${process.env.API_ORDERS}/stats`, {
        withCredentials: true,
      })
      .then(({ data }) => {
        setStats(data);
        setIsLoading(false);
      })
      .catch(() => {
        createNotification(
          INotificationType.ERROR,
          "Erreur, veuillez réessayer plus tard"
        );
        setIsLoading(false);
      });
  }, []);

  if (isLoading) return <LoadingPage />;
  return (
    <>
      <Head>
        <title>Staff - Statistiques</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section title="Statistiques">
        <Container className={s.container}>
          {stats && (
            <>
              <ActionCard
                title="CA Globale"
                img="/assets/benef.png"
                desc={`${stats.turnOver} €`}
              />
              <ActionCard
                title="Nombre de restaurants"
                img="/assets/default/defaultRestaurant.png"
                desc={stats.nbRestaurants}
              />
              <ActionCard
                title="Commandes complétés"
                img="/assets/accept.png"
                desc={stats.nbCompletedOrders}
              />
              <ActionCard
                title="Commandes refusés"
                img="/assets/declined.png"
                desc={stats.nbRefusedOrders}
              />
            </>
          )}
        </Container>
      </Section>
    </>
  );
};

Stats.requireAuth = "commercial";

export default Stats;
