import { Section } from "@ceseatslib/template";
import { Container } from "@mui/material";
import Head from "next/head";
import s from "styles/Wallets.module.scss";
import React, { useEffect, useRef } from "react";
import { IOrderAction, useStore } from "src/utils/hooks";
import { ActionCard } from "@ceseatslib/ui";
import axios from "axios";

const DeliveryPage = () => {
  const { orders, dispatchOrders } = useStore();
  const timer = useRef();

  useEffect(() => {
    timer.current = setInterval(() => {
      axios
        .get(`${process.env.API_ORDERS}/me?completed=false`, {
          withCredentials: true,
        })
        .then(({ data }) => {
          dispatchOrders({
            payload: data,
            type: IOrderAction.SET_ORDER,
          });
        })
        .catch(() => {
          console.log("error");
        });
    }, 3000);

    return () => clearTimeout(timer.current);
  }, [orders]);

  return (
    <>
      <Head>
        <title>Clients - Livraisons</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section title="Livraisons">
        <Container className={s.container}>
          {orders.order.length !== 0 &&
            orders.order.map((o, i) => (
              <ActionCard
                key={o._id}
                img="/assets/default/defaultOrder.png"
                title={`Order ${o.code ? o.code : i + 1}`}
                desc={o.orderStatus.title}
              />
            ))}
        </Container>
      </Section>
    </>
  );
};

export default DeliveryPage;
