import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Button, Card } from "cel";
import { Section } from "cel/ui";
import { OfferCard } from "cel/ui/cards";
import {
  INotificationType,
  useNotificationCenter,
} from "cel/utils/notifications";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  const { createNotification } = useNotificationCenter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button
        type="button"
        onClick={() =>
          createNotification(INotificationType.SUCCESS, "Hello World !")
        }
      >
        Add Notification
      </button>
      <Button />
      <Card src="/favicon.ico" alt="Logo NextJS" />

      <main className={styles.main}>
        <Section
          title="Les autres offres"
          description="Pour trouver votre bonheur"
        >
          <OfferCard
            img={{ src: "" }}
            title="HI"
            description="Hello"
            link={{ text: "Yo", href: "http://google.com" }}
          />
        </Section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};
export default Home;
