import { INotificationType, useNotificationCenter } from "@ceseatslib/utils";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { createNotification } = useNotificationCenter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Dev Tiers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Dev Tiers</h1>
        <button
          type="button"
          onClick={() =>
            createNotification(
              INotificationType.INFO,
              "Ceci est une notification"
            )
          }
        >
          Send notif
        </button>
      </main>
    </div>
  );
};

export default Home;
