enum IRestaurantAction {
  SET = "SET",
  ADD_ARTICLE = "ADD_ARTICLE",
  UPDATE_ARTICLE = "UPDATE_ARTICLE",
  DELETE_ARTICLE = "DELETE_ARTICLE",
  ADD_MENU = "ADD_MENU",
  UPDATE_MENU = "UPDATE_MENU",
  DELETE_MENU = "DELETE_MENU",
  DELETE = "DELETE",
}

export default IRestaurantAction;
