import React, { useState } from "react";
import Head from "next/head";
import { Section } from "@ceseatslib/template";
import { Button, Container, Typography } from "@mui/material";
import { AddressInput, addressSchema, IAddress } from "@ceseatslib/form";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";
import s from "styles/DriverHome.module.scss";
import Dashboard from "@components/dashboard";

const HomePage = () => {
  const [isListening, setIsListening] = useState(false);
  const methods = useForm<IAddress>({
    mode: "onChange",
    resolver: yupResolver(addressSchema),
  });

  const startListening = (isOkay) => {
    setIsListening(isOkay);
  };

  return (
    <div>
      <Head>
        <title>Livreurs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section title="Dashboard">
        <Container className={s.container}>
          {!isListening ? (
            <AddressInput
              methods={methods}
              name="address"
              label="Adresse"
              fullWidth
            />
          ) : (
            <Typography className={s.address}>
              {methods.getValues("address").label}
            </Typography>
          )}
          <Button
            variant="outlined"
            color={isListening ? "warning" : "success"}
            onClick={() => startListening(!isListening)}
            disabled={!methods.formState.isValid}
          >
            {isListening ? "Arrêter d'écouter" : "Se mettre en écoute"}
          </Button>
        </Container>
        {isListening && <Dashboard address={methods.getValues("address")} />}
      </Section>
    </div>
  );
};

HomePage.requireAuth = true;

export default HomePage;
