import { LoadingPage, Section } from "@ceseatslib/template";
import { ActionCard } from "@ceseatslib/ui";
import { INotificationType, useNotificationCenter } from "@ceseatslib/utils";
import { Container } from "@mui/material";
import axios from "axios";
import Head from "next/head";
import { useEffect, useState } from "react";
import s from "styles/Stats.module.scss";

const Stats = () => {
  const [stats, setStats] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const { createNotification } = useNotificationCenter();

  useEffect(() => {
    setIsLoading(true);
    axios
      .get(`${process.env.API_ORDERS}/restaurants/stats/me`, {
        withCredentials: true,
      })
      .then(({ data }) => {
        setStats(data);
        setIsLoading(false);
      })
      .catch(() => {
        createNotification(
          INotificationType.ERROR,
          "Erreur, veuillez réessayer plus tard"
        );
        setIsLoading(false);
      });
  }, []);

  if (isLoading) return <LoadingPage />;
  return (
    <>
      <Head>
        <title>Restaurateur - Statistiques</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section title="Statistiques">
        <Container className={s.container}>
          {stats && (
            <>
              <ActionCard
                title="Commandes complétés"
                img="/assets/accept.png"
                desc={stats.nbCompletedOrders}
              />
              <ActionCard
                title="Nombre d'articles"
                img="/assets/default/defaultArticle.png"
                desc={stats.nbArticles}
              />
              <ActionCard
                title="Nombre de menus"
                img="/assets/default/defaultArticle.png"
                desc={stats.nbMenus}
              />
              <ActionCard
                title="Commandes refusés"
                img="/assets/declined.png"
                desc={stats.nbRefusedOrders}
              />
            </>
          )}
        </Container>
      </Section>
    </>
  );
};

Stats.requireAuth = "restaurant";

export default Stats;
