import { PrimaryTemplate } from "@ceseatslib/template";
import { INotificationType, useNotificationCenter } from "@ceseatslib/utils";
import CartSummary from "@components/Cart";
import {
  Button,
  Container,
  FormControl,
  InputLabel,
  MenuItem,
  Select,
  Typography,
} from "@mui/material";
import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { IOrderAction, useStore } from "src/utils/hooks";
import s from "styles/Confirm.module.scss";

const ConfirmPage = () => {
  const [wallets, setWallets] = useState([]);
  const [selectedWallet, setSelectedWallet] = useState(null);
  const { createNotification } = useNotificationCenter();
  const router = useRouter();
  const { id } = router.query;
  const { cart, dispatchOrders } = useStore();

  useEffect(() => {
    if (!id) {
      router.push(`/restaurants`);
    } else if (!cart[id]) {
      router.push(`/restaurants/${id}`);
    }
  }, [id]);

  useEffect(() => {
    axios
      .get(`${process.env.API_WALLET}`, { withCredentials: true })
      .then(({ data }) => {
        setWallets(data);
      })
      .catch(() => {
        createNotification(
          INotificationType.ERROR,
          "Erreur, veuillez réessayer plus tard"
        );
      });
  }, []);

  const submitOrder = () => {
    console.log(cart);
    const formData = {
      summary: {
        articles: cart[id].articles.map((article) => ({
          _id: article._id,
          quantity: article.quantity,
        })),
        menus: cart[id].menus.map((menu) => ({
          _id: menu._id,
          quantity: menu.quantity,
        })),
      },
      restaurant: id,
      address: cart.address,
    };

    axios
      .post(`${process.env.API_ORDERS}/me`, formData, { withCredentials: true })
      .then(({ data }) => {
        dispatchOrders({
          type: IOrderAction.ADD_ORDER,
          payload: data,
        });
        router.push("/delivery");
      })
      .catch(() => {
        console.log("error");
        createNotification(
          INotificationType.ERROR,
          "Erreur, veuillez réessayer plus tard"
        );
      });
  };

  return (
    <>
      <Head>
        <title>Clients - Confirmation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className={s.loginContainer}>
        {cart[id] && (
          <PrimaryTemplate
            img={{ src: "/assets/confirmOrder.png", alt: "Image de commande" }}
          >
            <Container className={s.cart}>
              <Typography className={s.cart_title} variant="h3">
                Panier
              </Typography>
              <Container className={s.cart_content}>
                <CartSummary
                  summary={{
                    articles: cart[id].articles,
                    menus: cart[id].menus,
                  }}
                  price={cart[id].price}
                  restaurantId={id}
                />
              </Container>
              <Container className={s.btn_container}>
                <FormControl fullWidth>
                  <InputLabel id="demo-simple-select-label">Carte</InputLabel>
                  <Select
                    defaultValue={{}}
                    className={s.wallet}
                    variant="standard"
                    onSelect={setSelectedWallet}
                  >
                    {wallets.length > 0 ? (
                      wallets.map((wallet) => (
                        <MenuItem
                          key={wallet.id}
                          value={wallet}
                          onClick={() => setSelectedWallet(wallet)}
                        >
                          {wallet.designation ||
                            (wallet.cardNumber &&
                              `**** ${wallet.cardNumber.slice(-4)}`)}
                        </MenuItem>
                      ))
                    ) : (
                      <Link href="/wallets/new">
                        <MenuItem>Ajouter une carte</MenuItem>
                      </Link>
                    )}
                  </Select>
                </FormControl>
                <Container className={s.btn_container2}>
                  <Link href={`/restaurants/${id}`}>
                    <Button className={s.pay} variant="outlined" color="error">
                      Retour
                    </Button>
                  </Link>
                  <Button
                    className={s.pay}
                    variant="outlined"
                    color="success"
                    disabled={!selectedWallet}
                    onClick={submitOrder}
                  >
                    Payer
                  </Button>
                </Container>
              </Container>
            </Container>
          </PrimaryTemplate>
        )}
      </Container>
    </>
  );
};

ConfirmPage.requireAuth = true;

export default ConfirmPage;
