import { LoadingPage, Section } from "@ceseatslib/template";
import { ActionCard } from "@ceseatslib/ui";
import { Button, Container } from "@mui/material";
import CheckBoxIcon from "@mui/icons-material/CheckBox";
import s from "styles/Wallets.module.scss";
import axios from "axios";
import Head from "next/head";
import React, { useEffect, useRef, useState } from "react";

const Dashboard = ({ address }) => {
  const [orders, setOrders] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const timer = useRef(null);

  useEffect(() => {
    timer.current = setInterval(() => {
      axios
        .get(
          `${process.env.API_ORDERS}/drivers/search?lat=${address.latitude}&lng=${address.longitude}`,
          {
            withCredentials: true,
          }
        )
        .then(({ data }) => {
          axios
            .get(
              `${process.env.API_ORDERS}/drivers/me?lat=${address.latitude}&lng=${address.longitude}`,
              {
                withCredentials: true,
              }
            )
            .then(({ data: formData }) => {
              setOrders([...data, ...formData]);
              console.log(data);
              setIsLoading(false);
            })
            .catch(() => {
              console.log("error");
            });
        })
        .catch(() => {
          console.log("error");
        });
    }, 10000);
  }, []);

  const NextStep = (id) => {
    axios
      .get(`${process.env.API_ORDERS}/drivers/next/${id}`, {
        withCredentials: true,
      })
      .then(({ data }) => {
        console.log(data);
      })
      .catch(() => {
        console.log("error");
      });
  };

  if (isLoading) return <LoadingPage />;

  return (
    <>
      <Head>
        <title>Livreurs - Livraisons</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section title="Livraisons">
        <Container className={s.container}>
          {orders.length !== 0 &&
            orders.map((o, i) => (
              <ActionCard
                key={o._id}
                img="/assets/default/defaultOrder.png"
                title={`Order ${o.code ? o.code : i + 1}`}
                desc={o.orderStatus.title}
              >
                {o.orderStatus.stateNumber === 2 && (
                  <Button
                    onClick={() => NextStep(o._id)}
                    sx={{ height: "10px" }}
                  >
                    <CheckBoxIcon />
                  </Button>
                )}
                {o.orderStatus.stateNumber === 5 && (
                  <Button
                    onClick={() => NextStep(o._id)}
                    sx={{ height: "10px" }}
                  >
                    <CheckBoxIcon />
                  </Button>
                )}
                {o.orderStatus.stateNumber === 6 && (
                  <Button
                    onClick={() => NextStep(o._id)}
                    sx={{ height: "10px" }}
                  >
                    <CheckBoxIcon />
                  </Button>
                )}
              </ActionCard>
            ))}
        </Container>
      </Section>
    </>
  );
};

export default Dashboard;
