import { ActionCard } from "@ceseatslib/ui";
import { Section } from "@ceseatslib/template";
import Link from "next/link";
import { Container } from "@mui/material";
import s from "styles/Wallets.module.scss";
import Head from "next/head";
import { useEffect, useState } from "react";
import axios from "axios";

const OrdersPage = () => {
  const [orders, setOrders] = useState([]);

  useEffect(() => {
    axios
      .get(`${process.env.API_ORDERS}/me?completed=true`, {
        withCredentials: true,
      })
      .then(({ data }) => {
        setOrders(data);
      })
      .catch(() => {
        console.log("error");
      });
  }, []);

  return (
    <>
      <Head>
        <title>Clients - Historique</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section title="Historique de commande">
        <Container className={s.container}>
          {orders.map((o) => (
            <Link href={`/orders/${o._id}`} key={o._id}>
              <a style={{ textDecoration: "none" }} href={`/orders/${o._id}`}>
                <ActionCard
                  img="/assets/Drivers.png"
                  title={o.restaurant.name}
                  desc={o.createdAt}
                />
              </a>
            </Link>
          ))}
        </Container>
      </Section>
    </>
  );
};

OrdersPage.requireAuth = true;

export default OrdersPage;
